In [96]:
import numpy as np
import cv2


def nothing(x):
    pass


cap = cv2.VideoCapture(0)
minH = 130
maxH = 160
minS = 10
maxS = 40
minV = 75
maxV = 130

cv2.namedWindow('HSVIED')

# create trackbars for color change
cv2.createTrackbar('MIN H','HSVIED',0,180,nothing)
cv2.createTrackbar('MAX H','HSVIED',0,180,nothing)
cv2.createTrackbar('MIN S','HSVIED',0,255,nothing)
cv2.createTrackbar('MAX S','HSVIED',0,255,nothing)
cv2.createTrackbar('MIN V','HSVIED',0,255,nothing)
cv2.createTrackbar('MAX V','HSVIED',0,255,nothing)
while 1:
    
    minH = cv2.getTrackbarPos('MIN H','HSVIED')
    maxH = cv2.getTrackbarPos('MAX H','HSVIED')
    minS = cv2.getTrackbarPos('MIN S','HSVIED')
    maxS = cv2.getTrackbarPos('MAX S','HSVIED')
    minV = cv2.getTrackbarPos('MIN V','HSVIED')
    maxV = cv2.getTrackbarPos('MAX V','HSVIED')
    
    low = np.array([minH,minS,minV])
    high = np.array([maxH,maxS,maxV])
    print(low)
    print(high)
    ret, img = cap.read()
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hsv = cv2.inRange(hsv,low,high)
    cv2.imshow('HSVIED',hsv)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()

[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]


[ 5 20 15]
[51 45 33]
[ 5 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[10 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[ 8 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 45 33]
[13 20 15]
[51 46 33]
[13 20 15]
[51 53 33]
[13 20 15]

[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]
[13 77 68]
[ 51 212 189]


[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 212 189]
[ 13  77 115]
[ 51 2

In [3]:
import numpy as np
import cv2


def nothing(x):
    pass


cap = cv2.VideoCapture(0)
minH =10
maxH = 50
minS = 77
maxS = 212
minV = 115
maxV = 189

while 1:
    
    
    low = np.array([minH,minS,minV])
    high = np.array([maxH,maxS,maxV])
    
    ret, img = cap.read()
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hsv = cv2.inRange(hsv,low,high)
    hsv = cv2.medianBlur(hsv,5)
    kernel=cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
    dilation = cv2.dilate(hsv,kernel,iterations = 1)
    image, contours, hierarchy = cv2.findContours(dilation,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    large_cnt= 0
    for i in range(len(contours)):
        if cv2.contourArea(contours[i]) > cv2.contourArea(contours[large_cnt]):
            large_cnt = i
    
    cv2.drawContours(img ,contours,large_cnt ,[0, 0, 255], 1 )
    cnt = contours[large_cnt]
    hull = cv2.convexHull(cnt,returnPoints = False)
    defects = cv2.convexityDefects(cnt,hull)

    for i in range(defects.shape[0]):
        s,e,f,d = defects[i,0]
        start = tuple(cnt[s][0])
        end = tuple(cnt[e][0])
        far = tuple(cnt[f][0])
        cv2.line(img,start,end,[0,255,0],2)
        cv2.circle(img,far,5,[0,0,255],-1)

    cv2.imshow('HSVIED',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()